name: Queste
version: '${version}'
main: com.convallyria.queste.Queste
api-version: 1.17
softdepend: [Languagy, RPGRegions, Citizens, PlaceholderAPI]
authors: [SamB440]
description: A river of adventure in a land of quests
website: https://fortitude.islandearth.net
